// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather;

#nullable disable

namespace Weather.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20220809104042_Relations5")]
    partial class Relations5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Weather.WeatherMeasurement", b =>
                {
                    b.Property<int>("WeatherMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherMeasurementId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<int>("WindStrength")
                        .HasColumnType("int");

                    b.HasKey("WeatherMeasurementId");

                    b.ToTable("WeatherMeasurements");
                });

            modelBuilder.Entity("Weather.WeatherMeasurement", b =>
                {
                    b.OwnsMany("Weather.WeatherPrediction", "WeatherPredictions", b1 =>
                        {
                            b1.Property<int>("ParentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<int>("TemperatureCPrediction")
                                .HasColumnType("int");

                            b1.Property<TimeSpan>("Time")
                                .HasColumnType("time");

                            b1.HasKey("ParentId", "Id");

                            b1.ToTable("WeatherPredictions");

                            b1.WithOwner()
                                .HasForeignKey("ParentId");
                        });

                    b.Navigation("WeatherPredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
